version: '3'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.1
    container_name: 'my-elasticsearch'
    network_mode: 'host'
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"

  grafana:
    image: grafana/grafana
    container_name: 'my-grafana'
    network_mode: 'host'
    ports:
      - '3000:3000'